name: Generate MiHomo-Hagezi RuleSets

on:
  workflow_dispatch:
    inputs:
      PRE_RELEASE:
        description: "Set as pre-release"
        required: false
        type: boolean
        default: false
  schedule:
    - cron: "50 5 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set ENV variables
        run: |
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "RELEASE_DATE=$(date +'%A %F %T %Z')" >> $GITHUB_ENV

      - name: Create release directory
        run: mkdir release

      - name: Generate clash mrs rules
        run: |
          MIHOMO_URL=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r '.assets[] | select(.name | test("mihomo-linux-amd64-v.*\\.gz$")) | .browser_download_url' | head -n 1)
          curl -sSLf "$MIHOMO_URL" -o mihomo.gz
          gunzip mihomo.gz
          chmod +x mihomo
          curl -sSLf https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro.plus-onlydomains.txt -o TempProPlus.txt
          grep -v '^#' TempProPlus.txt > TempProPlusNew.txt
          sed 's/^/+./' TempProPlusNew.txt > HageziProPlus.txt
          ./mihomo convert-ruleset domain text HageziProPlus.txt HageziProPlus.mrs

      - name: Delete temp files
        run: |
          mv HageziProPlus.txt release/
          mv HageziProPlus.mrs release/
          rm TempProPlusNew.txt
          rm TempProPlus.txt
          rm mihomo

      - name: Generate Release Notes
        run: |
          echo "* Updated on ${{ env.RELEASE_DATE }}" > RELEASE_NOTES

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Generating MiHomo-Hagezi RuleSets ${{ env.RELEASE_DATE }}'
          push: true
          cwd: .
          default_author: github_actions
          fetch: --tags --force
          pathspec_error_handling: ignore
